[package]
name = "git-mob-rs"
version = "0.1.0"
authors = ["Jeremy Plsek <jeremyplsek@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "1.0.5"
clap = "3.0.0-beta.2"
git2 = "0.13.18"
open = "1.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
