on: [push, pull_request]

name: ci

jobs:
  tests:
    name: Test and Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Check spelling
        uses: codespell-project/actions-codespell@v2

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Run cargo check
        run: cargo check

      - name: Run cargo test
        run: cargo test

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings

  artifact:
    needs: tests
    if: github.ref == 'refs/heads/main'
    name: Create artifact
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Run cargo release build
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: git-mob-rs-${{ matrix.os }}
          path: |
            target/release/git-*
            !target/release/git-*.d
